services:
  - type: web
    name: logo-cluster-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app.app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production 