services:
  - type: web
    name: logoclusterapp
    env: node
    buildCommand: git lfs install && git lfs pull && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 